### ISSUE TITLE
tiddlydesktop-macapplesilicon-v0.0.18.zip

### ISSUE THREAD

**Issue by Kirchheim** [TiddlyWiki/TiddlyDesktop#281] opened 2023-07-16 12:05 UTC
Can't start, says file is damaged. Using an M2 MacBook Pro.

**Comment by Jermolene** [comment] 2023-07-16 19:50
Thank you @Kirchheim this is a duplicate of #276, please follow the discussion there.

**Closed by Jermolene** 2023-07-16 19:50 UTC
